In [19]:
import pandas as pd

In [20]:
df = pd.read_csv('salaries_by_college_major.csv')

In [21]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,"46,000.00","77,100.00","42,200.00","152,000.00",Business
1,Aerospace Engineering,"57,700.00","101,000.00","64,300.00","161,000.00",STEM
2,Agriculture,"42,600.00","71,900.00","36,300.00","150,000.00",Business
3,Anthropology,"36,800.00","61,500.00","33,800.00","138,000.00",HASS
4,Architecture,"41,600.00","76,800.00","50,600.00","136,000.00",Business

In [22]:
df.shape

(51, 6)

In [23]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [24]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [25]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [26]:
clean_df = df.dropna()

In [27]:
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,"40,800.00","78,200.00","41,200.00","168,000.00",HASS
46,Psychology,"35,900.00","60,400.00","31,600.00","127,000.00",HASS
47,Religion,"34,100.00","52,000.00","29,700.00","96,400.00",HASS
48,Sociology,"36,500.00","58,200.00","30,700.00","118,000.00",HASS
49,Spanish,"34,000.00","53,100.00","31,000.00","96,400.00",HASS

In [28]:
clean_df['Starting Median Salary']

0    46,000.00
1    57,700.00
2    42,600.00
3    36,800.00
4    41,600.00
5    35,800.00
6    38,800.00
7    43,000.00
8    63,200.00
9    42,600.00
10   53,900.00
11   38,100.00
12   61,400.00
13   55,900.00
14   53,700.00
15   35,000.00
16   35,900.00
17   50,100.00
18   34,900.00
19   60,900.00
20   38,000.00
21   37,900.00
22   47,900.00
23   39,100.00
24   41,200.00
25   43,500.00
26   35,700.00
27   38,800.00
28   39,200.00
29   37,800.00
30   57,700.00
31   49,100.00
32   36,100.00
33   40,900.00
34   35,600.00
35   49,200.00
36   40,800.00
37   45,400.00
38   57,900.00
39   35,900.00
40   54,200.00
41   39,900.00
42   39,900.00
43   74,300.00
44   50,300.00
45   40,800.00
46   35,900.00
47   34,100.00
48   36,500.00
49   34,000.00
Name: Starting Median Salary, dtype: float64

In [29]:
m=clean_df['Starting Median Salary'].max()
print(f"The highest is {m}")

The highest is 74300.0

In [30]:
n=clean_df['Starting Median Salary'].idxmax()
print(f"The index is {n}")

The index is 43

In [31]:
clean_df['Undergraduate Major'].loc[n]

'Physician Assistant'

In [32]:

clean_df.loc[n]

Undergraduate Major                  Physician Assistant
Starting Median Salary                         74,300.00
Mid-Career Median Salary                       91,700.00
Mid-Career 10th Percentile Salary              66,400.00
Mid-Career 90th Percentile Salary             124,000.00
Group                                               STEM
Name: 43, dtype: object

In [33]:
info=clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])
clean_df.insert(1,"Spread",info)

In [34]:
lr=clean_df.sort_values("Spread")
lr[['Undergraduate Major','Spread']]

                     Undergraduate Major     Spread
40                               Nursing  50,700.00
43                   Physician Assistant  57,600.00
41                             Nutrition  65,300.00
49                               Spanish  65,400.00
27            Health Care Administration  66,400.00
47                              Religion  66,700.00
23                              Forestry  70,000.00
32                       Interior Design  71,300.00
18                             Education  72,700.00
15                      Criminal Justice  74,800.00
26                        Graphic Design  76,000.00
31           Information Technology (IT)  84,500.00
10                     Civil Engineering  84,600.00
4                           Architecture  85,400.00
48                             Sociology  87,300.00
29                 Hospitality & Tourism  88,500.00
24                             Geography  92,000.00
46                            Psychology  95,400.00
12                  Computer Engineering  95,900.00
5                            Art History  96,200.00
1                  Aerospace Engineering  96,700.00
13                      Computer Science  98,000.00
6                                Biology  98,100.00
19                Electrical Engineering  98,700.00
38                Mechanical Engineering  99,300.00
20                               English  99,600.00
35  Management Information Systems (MIS) 100,700.00
21                                  Film 102,100.00
9                              Chemistry 102,700.00
3                           Anthropology 104,200.00
11                        Communications 105,500.00
34                            Journalism 106,600.00
39                                 Music 107,300.00
7                    Business Management 108,200.00
0                             Accounting 109,800.00
25                               Geology 111,000.00
28                               History 112,000.00
2                            Agriculture 113,700.00
14                          Construction 114,700.00
30                Industrial Engineering 115,900.00
16                                 Drama 116,300.00
33               International Relations 118,800.00
44                               Physics 122,000.00
8                   Chemical Engineering 122,100.00
45                     Political Science 126,800.00
42                            Philosophy 132,500.00
36                             Marketing 132,900.00
37                                  Math 137,800.00
22                               Finance 147,800.00
17                             Economics 159,400.00

In [35]:
clean_df.groupby("Group").count()

,Undergraduate Major,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,
Business,12,12,12,12,12,12
HASS,22,22,22,22,22,22
STEM,16,16,16,16,16,16

In [37]:
pd.options.display.float_format = '{:,.2f}'.format
clean_df.groupby("Group").mean(numeric_only=True)

,Spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,
Business,"103,958.33","44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"95,218.18","37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"101,600.00","53,862.50","90,812.50","56,025.00","157,625.00"